export const SITE = {
  name: 'Lumen Connection',
  url: process.env.NEXT_PUBLIC_SITE_URL ?? 'https://lumenconnection.com.br',
  locale: 'pt_BR',
  description:
    'Estúdio digital que une engenharia de software e produção visual de alta fidelidade. Web, mobile, branding, vídeo e 3D. João Pessoa, PB.',
  shortDescription: 'O elo entre engenharia digital e estética visual.',
  themeColor: '#0a0a0a',
  ogImage: '/og-image.png',
  ogImageWidth: 1200,
  ogImageHeight: 630,
  keywords: [
    'Lumen Connection',
    'Estúdio Digital',
    'Desenvolvimento Web',
    'Desenvolvimento de Software',
    'Desenvolvimento Mobile',
    'Edição de Vídeo',
    'Design Gráfico',
    'Branding',
    'Identidade Visual',
    'Modelagem 3D',
    'Blender',
    'VFX',
    'Next.js',
    'React',
    'João Pessoa',
    'Paraíba',
  ],
} as const
